Vagrant.configure("2") do |config|

    config.vm.define "Server" do |control|
    control.vm.box = "generic/debian11"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.hostname = "bbrahimS"
    control.vm.provision "shell", path: "scripts/controller.sh"
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
      vb.cpus = 1
    end
  
  end