Vagrant.configure("2") do |config|

  config.vm.define "Server" do |control|
  control.vm.box = "generic/debian11"
  control.vm.network "private_network", ip: "192.168.56.110"
  control.vm.hostname = "bbrahimS"
  end

  config.vm.define "ServerWorker" do |control|
  control.vm.box = "generic/debian11"
  control.vm.network "private_network", ip: "192.168.56.111"
  control.vm.hostname = "bbrahimSW"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

end
